replicaCount: 1
image:
  repository: us-central1-docker.pkg.dev/focal-psyche-460009-a5/bifrost/devplatform
  tag: 6bfb602
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  subdomain: devplatform
  # baseUrl is saastack.site as requested
  baseUrl: saastack.site
resources: {}